server:
  port: "8080"

db:
  host: "db"
  port: "5432"
  username: "postgres"
  password: "postgres"
  database: "eventgrid"
  sslmode: "disable"

queue:
  protocol: "amqp"
  host: "rabbitmq"
  username: "rabbitmquser"
  password: "rabbitmqpassword"
  port: "5672"

jwt:
  secret: "secret"
  ttl: 1
  unit: days # days, hours, minutes
