server:
  port: "8080"

db:
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "postgres"
  database: "eventgrid"
  sslmode: "disable"

jwt:
  secret: "secret"
  ttl: 1
  unit: days # days, hours, minutes
